-- General
vim.opt.number = true	
vim.opt.relativenumber = true	
vim.opt.linebreak = true	
vim.opt.textwidth = 100	
vim.opt.showmatch = false	
 
vim.opt.hlsearch = true	
vim.opt.smartcase = true	
vim.opt.ignorecase = true	
vim.opt.incsearch = true	
 
vim.opt.autoindent = true	
vim.opt.expandtab = true	
vim.opt.shiftwidth = 4	
vim.opt.smartindent = true	
vim.opt.smarttab = true	
vim.opt.softtabstop = 4	
 
-- Generated by VimConfig.com and adapted as a .lua file
