# Change leader binding
unbind C-b
set-option -g prefix C-Space
bind-key C-space send-prefix

# change split pane binding
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Shortcut for reloading
bind r source-file ~/.config/tmux/tmux.conf

# Mouse mode
set -g mouse on

# Set keys to vim style
set -g mode-keys vi

# Assign the vim copy key to clipboard copying
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -sel clipboard"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -sel clipboard"

# Disable auto rename
set-option -g allow-rename off

# Start windows at 1 (easy keyboard access)
set -g base-index 1

# Terminal colors
set-option -sa terminal-features ',term-256color:RGB'
set-option -ga terminal-overrides ',term-256color:Tc'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Themes
set -g @plugin "arcticicestudio/nord-tmux"

run '/usr/share/tmux-plugin-manager/tpm'
